name: smart_env
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  dotenv: ^4.1.0
  json_schema: ^5.1.3
  logging: ^1.2.0
  meta: ^1.11.0
  prompts: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7

executables:
  smart-env: smart_env

